"""Add return conditions and equipment counts

Revision ID: 556d44e96182
Revises: 
Create Date: 2025-10-27 14:49:18.847434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556d44e96182'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damaged_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lost_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('issued_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_condition', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_returned', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_equipment', schema=None) as batch_op:
        batch_op.drop_column('date_returned')
        batch_op.drop_column('return_condition')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('lost_count')
        batch_op.drop_column('damaged_count')

    # ### end Alembic commands ###
