"""add category_code to equipment

Revision ID: 79d53238989b
Revises: 556d44e96182
Create Date: 2025-11-10 10:41:08.978183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d53238989b'
down_revision = '556d44e96182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_code', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['category_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('category_code')

    # ### end Alembic commands ###
